-- WAYFOUND Phase 15: verified starter source registry for autonomous discovery.
-- This migration adds source configuration only. It does not create opportunities,
-- weaken publication gates, or enable production scheduling.

-- Historical integration fixtures used reserved example.test domains. If a prior
-- interrupted cleanup left them behind, make them explicitly non-operational.
update public.source_registry
set
  source_type = 'fixture',
  is_official_source = false,
  is_allowed = false,
  discovery_method = 'fixture',
  robots_policy_status = 'review_required',
  terms_review_status = 'not_reviewed',
  active = false,
  is_fixture = true,
  updated_at = timezone('utc', now())
where canonical_domain like '%.example.test'
   or canonical_domain = 'example.test';

insert into public.source_registry (
  source_name,
  source_type,
  base_url,
  canonical_domain,
  country_id,
  trust_tier,
  is_official_source,
  is_allowed,
  discovery_method,
  refresh_frequency_hours,
  crawl_policy_notes,
  robots_policy_status,
  terms_review_status,
  parser_adapter_identifier,
  active,
  internal_notes,
  is_fixture,
  adapter_identifier,
  adapter_version,
  allowed_domains,
  request_timeout_ms,
  response_size_limit_bytes,
  redirect_limit,
  concurrency_limit,
  retry_limit,
  monitoring_method,
  crawl_delay_ms
)
values
  (
    'China Scholarship Council Campus China',
    'official_scholarship_body',
    'https://www.campuschina.org/',
    'campuschina.org',
    (select id from public.countries where iso_alpha2 = 'CN'),
    1,
    true,
    false,
    'official_feed',
    24,
    'Official status verified through Chinese diplomatic-mission guidance linking applicants to the China Scholarship Council portal. Automated access returned a policy response on 2026-09-13; retrieval requires manual policy review.',
    'review_required',
    'not_reviewed',
    'phase15.generic-html',
    false,
    'Verified 2026-09-13. Unsupported for autonomous retrieval until robots and terms review is completed.',
    false,
    'phase15.native',
    'phase15.v1',
    array['campuschina.org', 'www.campuschina.org'],
    10000,
    1048576,
    2,
    1,
    1,
    'static_html',
    5000
  ),
  (
    'UK Government Find a Job',
    'official_government',
    'https://findajob.dwp.gov.uk/search',
    'findajob.dwp.gov.uk',
    (select id from public.countries where iso_alpha2 = 'GB'),
    1,
    true,
    false,
    'official_feed',
    12,
    'Official service verified through GOV.UK. The robots endpoint returned a failover page rather than a machine-readable policy on 2026-09-13, so automated retrieval is withheld pending review.',
    'review_required',
    'not_reviewed',
    'phase15.generic-html',
    false,
    'Verified 2026-09-13. No claim is made that listed vacancies provide sponsorship.',
    false,
    'phase15.native',
    'phase15.v1',
    array['findajob.dwp.gov.uk'],
    10000,
    1048576,
    2,
    1,
    1,
    'static_html',
    5000
  ),
  (
    'Government of Canada Job Bank',
    'official_government',
    'https://www.jobbank.gc.ca/findajob',
    'jobbank.gc.ca',
    (select id from public.countries where iso_alpha2 = 'CA'),
    1,
    true,
    true,
    'official_feed',
    12,
    'Government of Canada public job-search service. robots.txt permits general access with a five-second crawl delay; reviewed 2026-09-13. Vacancy-level immigration or sponsorship claims still require explicit evidence.',
    'allowed',
    'approved',
    'phase15.generic-html',
    true,
    'Official status and public retrieval path verified 2026-09-13.',
    false,
    'phase15.native',
    'phase15.v1',
    array['jobbank.gc.ca', 'www.jobbank.gc.ca'],
    10000,
    1048576,
    2,
    1,
    1,
    'static_html',
    5000
  ),
  (
    'CSIRO Careers',
    'official_employer',
    'https://jobs.csiro.au/',
    'jobs.csiro.au',
    (select id from public.countries where iso_alpha2 = 'AU'),
    1,
    true,
    true,
    'official_feed',
    12,
    'Official CSIRO careers service covering jobs, fellowships and studentships. robots.txt allows public listing pages while excluding application and account flows; reviewed 2026-09-13.',
    'allowed',
    'approved',
    'phase15.generic-html',
    true,
    'Official employer domain and bounded public retrieval path verified 2026-09-13.',
    false,
    'phase15.native',
    'phase15.v1',
    array['jobs.csiro.au'],
    10000,
    1048576,
    2,
    1,
    1,
    'static_html',
    2000
  ),
  (
    'Make it in Germany job listings',
    'official_government',
    'https://www.make-it-in-germany.com/en/working-in-germany/job-listings',
    'make-it-in-germany.com',
    (select id from public.countries where iso_alpha2 = 'DE'),
    1,
    true,
    true,
    'official_feed',
    12,
    'Official German government portal for qualified professionals. robots.txt allows public pages and publishes a sitemap; reviewed 2026-09-13. Listings do not imply sponsorship without vacancy-specific evidence.',
    'allowed',
    'approved',
    'phase15.generic-html',
    true,
    'Official government information and jobs domain verified 2026-09-13.',
    false,
    'phase15.native',
    'phase15.v1',
    array['make-it-in-germany.com', 'www.make-it-in-germany.com'],
    10000,
    1048576,
    2,
    1,
    1,
    'static_html',
    2000
  ),
  (
    'Research Ireland funding programmes',
    'official_scholarship_body',
    'https://www.researchireland.ie/funding/',
    'researchireland.ie',
    (select id from public.countries where iso_alpha2 = 'IE'),
    1,
    true,
    true,
    'official_feed',
    24,
    'Official national research and innovation funding programmes. robots.txt allows public programme pages and publishes a sitemap; reviewed 2026-09-13.',
    'allowed',
    'approved',
    'phase15.generic-html',
    true,
    'Official funding body and public programme catalogue verified 2026-09-13.',
    false,
    'phase15.native',
    'phase15.v1',
    array['researchireland.ie', 'www.researchireland.ie'],
    10000,
    1048576,
    2,
    1,
    1,
    'static_html',
    2000
  ),
  (
    'University of Amsterdam vacancies',
    'official_university',
    'https://werkenbij.uva.nl/en/vacancies',
    'werkenbij.uva.nl',
    (select id from public.countries where iso_alpha2 = 'NL'),
    1,
    true,
    true,
    'official_feed',
    12,
    'Official University of Amsterdam vacancy service. robots.txt allows unfiltered vacancy pages, publishes a sitemap and requests a one-second delay for named automated agents; reviewed 2026-09-13.',
    'allowed',
    'approved',
    'phase15.generic-html',
    true,
    'Official university careers domain and current research vacancies verified 2026-09-13.',
    false,
    'phase15.native',
    'phase15.v1',
    array['werkenbij.uva.nl', 'uva.nl', 'www.uva.nl'],
    10000,
    1048576,
    2,
    1,
    1,
    'json_ld',
    1000
  ),
  (
    'USAJOBS Early Careers',
    'official_government',
    'https://intern.usajobs.gov/search/',
    'usajobs.gov',
    (select id from public.countries where iso_alpha2 = 'US'),
    1,
    true,
    true,
    'official_feed',
    12,
    'Official United States federal early-career and internship service. robots.txt allows public search and announcement pages while excluding static service paths; reviewed 2026-09-13.',
    'allowed',
    'approved',
    'phase15.generic-html',
    true,
    'Official federal hiring service and public early-career search verified 2026-09-13.',
    false,
    'phase15.native',
    'phase15.v1',
    array['usajobs.gov', 'www.usajobs.gov', 'intern.usajobs.gov'],
    10000,
    1048576,
    2,
    1,
    1,
    'json_ld',
    2000
  ),
  (
    'New Zealand Government Jobs',
    'official_government',
    'https://jobs.govt.nz/',
    'jobs.govt.nz',
    (select id from public.countries where iso_alpha2 = 'NZ'),
    1,
    true,
    false,
    'official_feed',
    12,
    'Official New Zealand public-service jobs gateway. DNS retrieval was unavailable from the verification environment on 2026-09-13, so autonomous access remains disabled pending a fresh policy review.',
    'review_required',
    'not_reviewed',
    'phase15.generic-html',
    false,
    'Official government source identified but not enabled for retrieval as of 2026-09-13.',
    false,
    'phase15.native',
    'phase15.v1',
    array['jobs.govt.nz'],
    10000,
    1048576,
    2,
    1,
    1,
    'static_html',
    5000
  )
on conflict (base_url) do update set
  source_name = excluded.source_name,
  source_type = excluded.source_type,
  canonical_domain = excluded.canonical_domain,
  country_id = excluded.country_id,
  trust_tier = excluded.trust_tier,
  is_official_source = excluded.is_official_source,
  is_allowed = excluded.is_allowed,
  discovery_method = excluded.discovery_method,
  refresh_frequency_hours = excluded.refresh_frequency_hours,
  crawl_policy_notes = excluded.crawl_policy_notes,
  robots_policy_status = excluded.robots_policy_status,
  terms_review_status = excluded.terms_review_status,
  parser_adapter_identifier = excluded.parser_adapter_identifier,
  active = excluded.active,
  internal_notes = excluded.internal_notes,
  is_fixture = excluded.is_fixture,
  adapter_identifier = excluded.adapter_identifier,
  adapter_version = excluded.adapter_version,
  allowed_domains = excluded.allowed_domains,
  request_timeout_ms = excluded.request_timeout_ms,
  response_size_limit_bytes = excluded.response_size_limit_bytes,
  redirect_limit = excluded.redirect_limit,
  concurrency_limit = excluded.concurrency_limit,
  retry_limit = excluded.retry_limit,
  monitoring_method = excluded.monitoring_method,
  crawl_delay_ms = excluded.crawl_delay_ms,
  updated_at = timezone('utc', now());
